#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export EDITOR='atom -w'

# Aliases
alias zshconfig="e ~/.zshrc"
alias git=hub
alias g=git
alias git-tower=gittower
alias twr=gittower
alias reload!="source ~/.zshrc"

## PATH ASSIGNMENTS

# Add Homebrew PATH
export PATH="/usr/local/bin:$PATH"

# Add Current Directory Path
export PATH="./bin:$PATH"

# Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

# PG App
PATH="/Applications/Postgres.app/Contents/Versions/9.3/bin:$PATH"

### Exports

# Set the bundler editor
export BUNDLER_EDITOR=mine

# Android SDK HOME
export ANDROID_HOME=/usr/local/opt/android-sdk

# Set the default provider
export VAGRANT_DEFAULT_PROVIDER=virtualbox

# Set the docker host
export DOCKER_HOST=tcp://docker.jasonwaldrip.com:4243

# Set the Development PATH
export DEVPATH=~/dev

# Set the Go path
export GOPATH=$DEVPATH
export PATH=$GOPATH/bin:$PATH

# Locate Atom
export ATOM_PATH=~/Applications

# The iTriage Gem Host
export ITRIAGE_GEM_HOST=https://developer:09763a8cd60c4621c633d6f7d275eadd74a7967343a780eddaf8897478452dbf@developers.itriagehealth.com/gems/

### RBENV SETUP
if which rbenv > /dev/null
  then
  # export RBENV_ROOT=/usr/local/var/rbenv
  eval "$(rbenv init -)"
  else
  echo "Warning, missing rbenv"
fi

### AUTOJUMP SETUP
if which autojump > /dev/null
    then
    [[ -s `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh
fi

### Functions

# A function to set the docker host
function set-docker-host () {

  if [ $1 ]
  then
  export DOCKER_HOST=$1

  elif [ -e ".docker_host" ]
  then
  export DOCKER_HOST=$(cat .docker_host)

  else
  echo "missing host argument"
  return

  fi

  print "docker host is now: $DOCKER_HOST"
}
