#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export EDITOR='subl -w'

# Aliases
alias zshconfig="e ~/.zshrc"
alias git=hub
alias g=git
alias git-tower=gittower
alias twr=gittower

# PATH
export PATH=./bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH

# rbenv setup
export RBENV_ROOT=/usr/local/var/rbenv
if which rbenv > /dev/null; then eval "$(rbenv init - zsh)"; fi

# Auto Jump
[[ -s `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh

alias reload!="source ~/.zshrc"

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

### Set the bundler editor
export BUNDLER_EDITOR=mine

### PG App
PATH="/Applications/Postgres.app/Contents/Versions/9.3/bin:$PATH"

# Always look in the local path first
export PATH=./bin:$PATH

# added by travis gem
# source /Users/jwaldrip/.travis/travis.sh

# Android SDK HOME
export ANDROID_HOME=/usr/local/opt/android-sdk

# Set the default provider
export VAGRANT_DEFAULT_PROVIDER=virtualbox

# Set the docker host
# export DOCKER_HOST=tcp://127.0.0.1:4243

# The iTriage Gem Host
ITRIAGE_GEM_HOST=https://developer:09763a8cd60c4621c633d6f7d275eadd74a7967343a780eddaf8897478452dbf@developers.itriagehealth.com/gems/

# A function to set the docker host
function set-docker-host () {
  
  if [ $1 ]
  then
  export DOCKER_HOST=$1
  
  elif [ -e ".docker_host" ]
  then
  export DOCKER_HOST=$(cat .docker_host)
  
  else
  echo "missing host argument" 
  return

  fi
  
  print "docker host is now: $DOCKER_HOST"
}
