#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export EDITOR='subl -w'

# Aliases
alias zshconfig="e ~/.zshrc"
alias git=hub
alias g=git
alias git-tower= gittower

# PATH
export PATH=./bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH

# rbenv setup
if which rbenv > /dev/null; then eval "$(rbenv init - zsh)"; fi

# Auto Jump
[[ -s `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh

alias reload!="source ~/.zshrc"

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

### Set the bundler editor
export BUNDLER_EDITOR=mine

### PG App
PATH="/Applications/Postgres93.app/Contents/MacOS/bin:$PATH"

# Always look in the local path first
export PATH=./bin:$PATH

# added by travis gem
# source /Users/jwaldrip/.travis/travis.sh
